version: 2

sources:
  - name: openaire
    description: 'Openaire research product'
    schema: ldg_openaire
    tables:
      - name: researchproduct
      - name: researchproduct2creator
      - name: researchproduct2measure
      - name: researchproduct2pid
      - name: researchproduct2relevantdate
      - name: researchproduct2subject