version: 2

sources:
  - name: openalex
    description: 'Openalex works'
    database: dw_cic
    schema: ldg_openalex
    tables:
      - name: author
      - name: institution
      - name: language
      - name: license
      - name: work
      - name: work2authorship
      - name: work2location
      - name: worktype