version: 2

sources:
  - name: openalex
    description: 'Openalex works'
    database: staging
    schema: stg_openalex
    tables:
      - name: dauthor
      - name: dinstitution
      - name: work