version: 2

sources:
  - name: oai
    description: 'DSpace database'
    database: staging
    schema: stg_oai
    tables:
      - name: item
      - name: item_doi
      - name: item_contributor
      - name: item_creator
      - name: item_isbn
      - name: item_issn
      - name: item_language
      - name: item_relation
      - name: item_subject
