version: 2

sources:
  - name: oai
    description: 'DSpace database'
    database: staging
    schema: stg_oai
    tables:
      - name: item
      - name: bridge_item_contributor
      - name: bridge_item_creator
      - name: bridge_item_language
      - name: bridge_item_relation
      - name: bridge_item_subject
      - name: bridge_item_doi
      - name: bridge_item_issn
      - name: bridge_item_isbn