version: 2

sources:
  - name: oai
    description: 'DSpace database'
    database: staging
    schema: stg_oai
    tables:
      - name: item
      - name: item2contributor
      - name: item2creator
      - name: item2doi
      - name: item2isbn
      - name: item2issn
      - name: item2language
      - name: item2subject
