version: 2

sources:
  - name: openaire_researchproduct_collectedfrom_datasource
    description: 'Openaire research product collected from datasource'
    database: dw_cic
    schema: ldg_openaire_collectedfrom_datasource
    tables:
      - name: researchproduct
      - name: researchproduct2author
      - name: researchproduct2originalId
      - name: researchproduct2subject