
version: 2

sources:
  - name: repository_db
    description: 'DSpace database'
    database: repository_db
    schema: source
    tables:
      - name: repository_db_bitstream
      - name: repository_db_bundle
      - name: repository_db_bundle2bitstream
      - name: repository_db_collection
      - name: repository_db_collection2item
      - name: repository_db_communities2item
      - name: repository_db_community
      - name: repository_db_community2collection
      - name: repository_db_community2community
      - name: repository_db_community2item
      - name: repository_db_handle
      - name: repository_db_doi
      - name: repository_db_item
      - name: repository_db_item2bundle
      - name: repository_db_metadatafieldregistry
      - name: repository_db_metadataschemaregistry
      - name: repository_db_metadatavalue
