version: 2

sources:
  - name: dspacedb
    description: 'DSpace database'
    database: staging
    schema: ldg_dspacedb
    tables:
      - name: bitstream
      - name: bundle
      - name: bundle2bitstream
      - name: collection
      - name: collection2item
      - name: communities2item
      - name: community
      - name: community2collection
      - name: community2community
      - name: community2item
      - name: handle
      - name: doi
      - name: item
      - name: item2bundle
      - name: metadatafieldregistry
      - name: metadataschemaregistry
      - name: metadatavalue
