{{ config(materialized='table')}}

with base as (
    select
        work_id,
        doi,
        title,
        display_name,
        {{ dbt_date.convert_timezone("publication_date") }} as publication_date,
        language,
        type,
        type_crossref,
        countries_distinct_count::int,
        institutions_distinct_count::int,
        fwci::float,
        has_fulltext,
        fulltext_origin,
        cited_by_count::int,
        is_retracted,
        is_paratext,
        locations_count::int,
        referenced_works_count::int,
        cited_by_api_url,
        {{ dbt_date.convert_timezone("updated_date") }} as updated_date,
        {{ dbt_date.convert_timezone("created_date") }} as created_date,
        mag,
        pmcid,
        pmid,
        biblio_first_page,
        biblio_issue,
        biblio_last_page,
        biblio_volume,
        any_repository_has_fulltext,
        is_oa,
        oa_status,
        oa_url,
        cited_by_percentile_year_max::int,
        cited_by_percentile_year_min::int,
        citation_normalized_percentile_is_in_top_10_percent,
        citation_normalized_percentile_is_in_top_1_percent,
        citation_normalized_percentile_value::float,
        apc_list_currency,
        apc_list_provenance,
        apc_list_value::float,
        apc_list_value_usd::float,
        apc_paid_currency,
        apc_paid_provenance,
        apc_paid_value::float,
        apc_paid_value_usd::float,
        indexed_in_arxiv,
        indexed_in_doaj,
        indexed_in_crossref,
        indexed_in_pubmed,
        load_datetime
    from {{ ref('base_work_openalex') }}
)
select * from base
  