version: 2

sources:
  - name: openaire_graph_researchproduct
    description: 'Openaire research product collected from datasource'
    database: dw_cic
    schema: ldg_openaire_graph
    tables:
      - name: researchproduct
      - name: researchproduct2author
      - name: researchproduct2originalId
      - name: researchproduct2subject