version: 2

sources:
  - name: openalex
    description: 'Openalex works'
    schema: ldg_openalex
    tables:
      - name: author
      - name: author2affiliation
      - name: author2institution
      - name: author2topic
#      - name: institution
      - name: language
      - name: license
      - name: work
      - name: work2author
      - name: work2concept
      - name: work2corresponding_author_ids
      - name: work2ids
      - name: work2primary_location
      - name: work2primary_topics
      - name: work2referenced_works
      - name: work2location
      - name: worktype