version: 2

sources:
  - name: openalex
    description: 'Openalex works'
    schema: ldg_openalex
    tables:
      - name: author
      - name: work
      - name: map_author_affiliation
      - name: map_author_institution
      - name: map_author_topic
#      - name: institution
      - name: language
      - name: license
      - name: map_work_author
      - name: map_work_concept
      - name: map_work_corresponding_author_ids
      - name: map_work_ids
      - name: map_work_primary_location
      - name: map_work_primary_topics
      - name: map_work_referenced_works
      - name: map_work_location
      - name: map_work_topics
      - name: worktype