version: 2

sources:
  - name: openaire
    description: 'Openaire research product'
    database: dw_cic
    schema: ldg_openaire
    tables:
      - name: researchproduct
      - name: researchproduct2measure
      - name: researchproduct2pid